# hyperparameter: dann, svhn -> mnist

batch=500
optimizer='adam'
weight_decay=0.0
keep_prob=1.0
n_thread=4
initializer='variance_scaling'
base_cell='cnn'
tfrecord_source='tfrecord/svhn'
tfrecord_target='tfrecord/mnist'

[config_learning_rate]
identity=true
initial_step=0.0002

[config_regularizer_domain_classifier]
identity=true
initial_step=1.0
#initial_step=0.0

[config_regularizer_feature_extractor]
exponential=true
multiplier=0.0004

[config_feature_extractor]
cnn_channel=[32, 32, 64, 64, 128, 128]
cnn_filter=[3, 3, 3, 3, 3, 3]
cnn_stride=[2, 2, 2, 2, 2, 2]
fc_n_hidden=128

[config_domain_classifier]
output_size=1

[config_classifier]
output_size=10
