# hyperparameter: deep_jdot, svhn -> mnist

# strong effect of optimal transport regularization
#alpha_distance=0.01
#lambda_target_loss=0.001

# paper's optimal setting
alpha_distance=0.001
lambda_target_loss=0.0001

# no optimal transport regularization
#alpha_distance=0.0
#lambda_target_loss=0.0

# following parameters are generic
batch=500
optimizer='adam'
keep_prob=1.0
n_thread=4
weight_decay=0.0
initializer='variance_scaling'
base_cell='cnn'
tfrecord_source='tfrecord/svhn'
tfrecord_target='tfrecord/mnist'

[learning_rate_config]
identity=true
initial_step=0.0002

[config_feature_extractor]
cnn_channel=[32, 32, 64, 64, 128, 128]
cnn_filter=[3, 3, 3, 3, 3, 3]
cnn_stride=[2, 2, 2, 2, 2, 2]
fc_n_hidden=128

[config_classifier]
output_size=10
